src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>FirstCompetitorAccept__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FirstCompetitorAccept</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FirstCompetitorScore__c</fullName>
        <defaultValue>0</defaultValue>
        <label>First Competitor Score</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FirstCompetitor__c</fullName>
        <label>FirstCompetitor</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecondCompetitorAccept__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SecondCompetitorAccept</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SecondCompetitorScore__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Second Competitor Score</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SecondCompetitor__c</fullName>
        <label>SecondCompetitor</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Game Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Upcoming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Round Robin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Elimination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double Elimination</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RoundRobin.cls
public with sharing class RoundRobin {
    Tournament__c tournament {get{
           return [Select type__c,status__c 
                   From Tournament__c 
                   where id=:ApexPages.currentPage().getParameters().get('id')];
    } set;}
    
    List<Game__C> games {get {
           return [Select id 
                   from Game__c 
                   where id=:tournament.id];
    } set;}
    
    List<String> allIds {get;set;}
    List<Game__c> currentTournamentGames{get;set;}
     
    public void RoundRobinTournament(){  
        if (games.size() == (allIds.size() * (allIds.size()-1))/2) return;
        for(Integer round=0; round<allIds.size();round++){
            for(Integer match=round+1;match<allIds.size();match++){
                    Game__c currentGame = new Game__c();
                    currentGame.FirstCompetitor__c = allIds.get(round); 
                    currentGame.SecondCompetitor__c = allIds.get(match);
                    currentGame.Tournament__c = tournament.Id;
                    currentTournamentGames.add(currentGame); 
            }
        } 
        upsert currentTournamentGames;
    }
     public List<List<String>> RoundRobinGrid() {
        Map<String, String> idNameMap = new Map<String,String>();
        List<List<String>> result = new List<List<String>>();
	List<String> Ids = new List<String>(idNameMap.keySet());
	List<String> firstRow = new List<String>();
	firstRow.add('-');
	for (String id : Ids) {
            firstRow.add(idNameMap.get(id));
	}
	result.add(firstRow);
	for (Integer i = 0; i < Ids.size(); i++) {
            List<String> row = new List<String>();
            row.add(idNameMap.get(Ids[i]));
            for (Integer j = 0; j < Ids.size(); j++) {
		if (i == j) {
                    row.add('-');
			} else {
				for (Game__c g : games) {
                                    if (g.firstCompetitor__c == Ids[i] && g.secondCompetitor__c == Ids[j]) {
					if (g.SecondCompetitorAccept__c && g.FirstCompetitorAccept__c) {
                                            row.add(String.valueOf(g.firstCompetitorScore__c));
					} else {
                                            row.add('0');
                                    }
				}
                                    if (g.firstCompetitor__c == Ids[j] && g.secondCompetitor__c == Ids[i]) {
					if (g.SecondCompetitorAccept__c && g.FirstCompetitorAccept__c) {
                                            row.add(String.valueOf(g.secondCompetitorScore__c));
                                            } else {
                                            row.add('0');
                                            }
                                        }
                                    }
                                }
                 }
            result.add(row);
        }
		
    return result;
    }
    public String getNameById(String getCurrentNameByThisId){
        Player__c player = [select name
                            from Player__c
                            where id=:getCurrentNameByThisId];
        if(player != null){
            return player.name;
        }else{
            Team__c team = [select name
                      from Team__c
                      where id=:getCurrentNameByThisId];
            return team.name;
        } 
    }
}