src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>FirstCompetitorScore__c</fullName>
        <defaultValue>0</defaultValue>
        <label>First Competitor Score</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FirstCompetitor__c</fullName>
        <label>FirstCompetitor</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecondCompetitorScore__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Second Competitor Score</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SecondCompetitor__c</fullName>
        <label>SecondCompetitor</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Game Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PlayerTeam__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>PlayerTeams</relationshipLabel>
        <relationshipName>PlayerTeams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>PlayerTeams</relationshipLabel>
        <relationshipName>PlayerTeams</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PlayerTeam</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>PlayerTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PlayerTeams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PlayerTournament__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PlayerTournament</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>PlayerTournament Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PlayerTournaments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <picklist>
            <picklistValues>
                <fullName>1 x 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 x 2</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Upcoming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GamesToPLayNotifier.cls
global class GamesToPLayNotifier implements Schedulable {
    
    public integer emailsCnt { get; set; }
    
    global void execute(SchedulableContext ctx) {
    	Set<String> emails = new Set<String>();
        List<Tournament__c> tournaments = [SELECT Id, Format__c FROM Tournament__c WHERE Status__c = 'Current'];
        for (Tournament__c t : tournaments) {
            if (t.Format__c == '1 x 1') {
                    emails.addAll(getPlayersEmails(t));
            } else {
                    emails.addAll(getTeamMembersEmails(t));
            }
        }
        emailsCnt = sendNotification(emails);
    }
    
    private Set<String> getPlayersEmails(Tournament__c tournament) {
    	Set<String> resultEmails = new Set<String>();
    	List<Player__c> players = [SELECT Email__c FROM Player__c WHERE Id IN
    		(SELECT Player__c FROM PlayerTournament__c WHERE Tournament__c = :tournament.Id)];
    	List<Game__c> games = [SELECT firstCompetitor__c, secondCompetitor__c FROM Game__c
    		WHERE Tournament__c = :tournament.Id AND firstCompetitorScore__c = 0
    		AND secondCompetitorScore__c = 0];
    	for (Player__c p : players) {
    		for (Game__c g : games) {
    			if (g.firstCompetitor__c == p.Id || g.secondCompetitor__c == p.Id) {
    				resultEmails.add(p.Email__c);
    				break;
    			}
    		}
    	}
    	return resultEmails;
    }
    
    private Set<String> getTeamMembersEmails(Tournament__c tournament) {
    	Set<String> resultEmails = new Set<String>();
    	List<Game__c> games = [SELECT firstCompetitor__c, secondCompetitor__c FROM Game__c
    		WHERE Tournament__c = :tournament.Id AND firstCompetitorScore__c = 0
    		AND secondCompetitorScore__c = 0];
    	Set<String> teamIds = new Set<String>();
    	for (Game__c g : games) {
    		teamIds.add(g.firstCompetitor__c);
    		teamIds.add(g.secondCompetitor__c);
    	}
    	List<Player__c> players = [SELECT Email__c FROM Player__c WHERE Id IN
    		(SELECT Player__c FROM PlayerTeam__c WHERE Team__c IN :teamIds)];
    	for (Player__c p : players) {
    		resultEmails.add(p.Email__c);
    	}
    	return resultEmails;
    }
    
    private integer sendNotification(Set<String> emails) {
        return emails.size();
    }
    
}