src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Game Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <picklist>
            <picklistValues>
                <fullName>1 x 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 x 2</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Upcoming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Round Robin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Elimination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double Elimination</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DoubleEliminationTournament_TEST.cls
@isTest
public with sharing class DoubleEliminationTournament_TEST {
    
    public static DoubleEliminationTournament det = new DoubleEliminationTournament();
    public static Tournament__c t = new Tournament__c(Name='qwer', Type__c='Double Elimination', Format__c='1 x 1', StartDate__c=DateTime.now(), Status__c='Upcoming');
    
    public static testMethod void testProperties() {
        
        System.assertEquals(1, det.competitorsName.size());
        
        det.oneTournament = new Tournament__c();
        
        System.assertEquals(0, det.representDoubleEliminationGrid.size());
        
        System.assertEquals(1, det.ijz);
        
        insert(t);
        det.oneTournament = t;
        
        System.assertEquals(1, det.competitorsName.size());
        System.assertEquals(1, det.representDoubleEliminationGrid.size());
    }
    
    public static testMethod void testGenerateRounds() {
        
        insert(t);
        
        DoubleEliminationTournament.generateRounds(new List<String>(), t.Id);
        
        Tournament__c t11 = [SELECT Id, Status__c FROM Tournament__c WHERE Id = :t.Id];
        
        System.assertEquals('Completed', t11.Status__c);
        
        t11.Status__c = 'Upcoming';
        update(t11);
        
        Player__c p0 = new Player__c(Email__c = 'vdv@vdv.dv', IsManager__c = true, Password__c = '1234567890', Name = 'bdf', Status__c = 'Active');
        insert (p0);
        Player__c p1 = new Player__c(Email__c = '1vdv@vdv.dv', IsManager__c = true, Password__c = '1234567890', Name = 'bdf', Status__c = 'Active');
        insert (p1);
        Player__c p2 = new Player__c(Email__c = '2vdv@vdv.dv', IsManager__c = true, Password__c = '1234567890', Name = 'bdf', Status__c = 'Active');
        insert (p2);
        
        List<Player__c> players = [select Id,Password__c from Player__c];
        
        List<String> ids = new List<String>();
        
        for (Player__c p : players) {
            ids.add(p.Id);
        }
        
        DoubleEliminationTournament.generateRounds(ids, t.Id);
        
        List<Game__c> games = [select Id from Game__c];
        
        System.assertEquals(3, games.size());
        
    }

}