src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>FirstCompetitor__c</fullName>
        <label>FirstCompetitor</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecondCompetitor__c</fullName>
        <label>SecondCompetitor</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Game Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PlayerTournament__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PlayerTournament</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>PlayerTournament Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PlayerTournaments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <picklist>
            <picklistValues>
                <fullName>1 x 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 x 2</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Upcoming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Round Robin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Elimination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double Elimination</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GameController_Test.cls
@isTest private static void testInsert(){
        Tournament__C tournament = new Tournament__c(name='ddd',format__c = '1 x 1',StartDate__c = Datetime.now(),Status__c='Current',type__c= 'Round Robin');  
        insert tournament;
        Player__c newPlayer1 = new Player__c(name = 'newPlayer1',email__c = 'dd@ddd.dd',IsManager__c=false,Password__c = '666666666',Status__c = 'Active');
        insert newPlayer1;
        Player__c newPlayer2 = new Player__c(name = 'newPlayer2',email__c = 'ddd@ddd.dd',IsManager__c=false,Password__c = '666666666',Status__c = 'Active');
        insert newPlayer2;
        Player__c newPlayer3 = new Player__c(name = 'newPlayer3',email__c = 'ddddd@ddd.dd',IsManager__c=false,Password__c = '666666666',Status__c = 'Active');
        insert newPlayer3;
        PlayerTournament__c playerTournament1 = new PlayerTournament__c();
        playerTournament1.Player__c = newPlayer1.Id;
        playerTournament1.Tournament__c = tournament.Id;
        insert playerTournament1;
        PlayerTournament__c playerTournament2 = new PlayerTournament__c();
        playerTournament2.Player__c = newPlayer2.Id;
        playerTournament2.Tournament__c = tournament.Id;
        insert playerTournament2;
        PlayerTournament__c playerTournament3 = new PlayerTournament__c();
        playerTournament3.Player__c = newPlayer3.Id;
        playerTournament3.Tournament__c = tournament.Id;
        insert playerTournament3;
        Game__c currentGame1 = new Game__c(FirstCompetitor__c = newPlayer1.id+'',SecondCompetitor__c=newPlayer2.id+'',Tournament__c =tournament.id);
        Game__c currentGame2 = new Game__c(FirstCompetitor__c = newPlayer1.id+'',SecondCompetitor__c=newPlayer3.id+'',Tournament__c =tournament.id);
        Game__c currentGame3 = new Game__c(FirstCompetitor__c = newPlayer2.id+'',SecondCompetitor__c=newPlayer3.id+'',Tournament__c =tournament.id);
        insert currentGame1;
        insert currentGame2;
        insert currentGame3;
        
        GameController g = new GameController();
        g.currentPlayer = newPlayer1;
        Test.startTest();
        g.insertScore();
        Test.stopTest();
    }
}