src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PlayerStatistics__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>PlayersStatistics</relationshipLabel>
        <relationshipName>PlayersStatistics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>PlayersStatistics</relationshipLabel>
        <relationshipName>PlayersStatistics</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PlayerStatistic</label>
    <nameField>
        <label>PlayerStatistics Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PlayersStatistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PlayerTournament__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PlayerTournament</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>PlayerTournament Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PlayerTournaments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Upcoming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlayersStatisticsGenerator.cls
public with sharing class PlayersStatisticsGenerator {
    public static void generatePlayerStatisticsObjects(
        List<Tournament__c> beforeUpdateTournaments,
        List<Tournament__c> afterUpdateTournaments
        ){
        System.debug('before update status: '+beforeUpdateTournaments.get(0).Status__c+' after update status: '+afterUpdateTournaments.get(0).Status__c);
        Map<Id,Tournament__c> tournamentsChangedToCurrentStatus = new Map<Id,Tournament__c>();
        List<PlayerTournament__c> playerTournamentsList = new List<PlayerTournament__c>();
        
        
        
        for (Integer i = 0; i < beforeUpdateTournaments.size(); i++){
            if (beforeUpdateTournaments.get(i).Status__c != 'Current' && afterUpdateTournaments.get(i).Status__c == 'Current'){
                tournamentsChangedToCurrentStatus.put(afterUpdateTournaments.get(i).Id,afterUpdateTournaments.get(i));
            }
        }
        
        playerTournamentsList = [select Player__c,Tournament__c from PlayerTournament__c where Tournament__c in:tournamentsChangedToCurrentStatus.keySet()];
        
        
        
        List<PlayerStatistics__c> playerStatisticList = new List<PlayerStatistics__c>();
        
       
            for (PlayerTournament__c playerTournament: playerTournamentsList){
                playerStatisticList.add(
                new PlayerStatistics__c(
                    Player__c = playerTournament.Player__c,
                    Tournament__c = playerTournament.Tournament__c
                ));
            }
        
        
        System.debug('size of player statistic list: '+playerStatisticList.size());
        
        insert playerStatisticList;
    }
}