src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PlayerTournament__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PlayerTournament</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>PlayerTournament Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PlayerTournaments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>IsComplete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsComplete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <picklist>
            <picklistValues>
                <fullName>1 x 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 x 2</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Upcoming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Round Robin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Elimination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double Elimination</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TournamentStarter.cls
global class TournamentStarter implements Schedulable {

    global void execute(SchedulableContext ctx) {
    	DateTime dt = DateTime.now();
        List<Tournament__c> tournamentsToStart = [SELECT Id, Name, Type__c, Format__c, Status__c, StartDate__c 
            FROM Tournament__c 
            WHERE Status__c = 'Upcoming' AND StartDate__c <= :dt];
        // Let's make a limit to start only 3 tournaments for one time to be sure that we will not exceed salesforce limits
        for(integer i = 0; i < (tournamentsToStart.size() > 3 ? 3 : tournamentsToStart.size()); i++) {
            try {
                tournamentsToStart[i].Status__c = 'Current';
                update(tournamentsToStart[i]);
                generateGames(tournamentsToStart[i]);
            } catch (Exception e) {
                System.debug(e);
            }
        }
    }
    
    private void generateGames(Tournament__c tournament) {
        List<String> ids = getCompetitorsIds(tournament);
        if (tournament.Type__c == 'Single Elimination') {
        	SingleEliminationTournament.StartSingleEliminationTournament(ids, tournament);
        } else if (tournament.Type__c == 'Double Elimination') {
        	DoubleEliminationTournament.generateRounds(ids, tournament.Id);
        } else {
            RoundRobin.RoundRobinTournament(tournament, ids);
        }
    }
    
    private List<String> getCompetitorsIds(Tournament__c tournament) {
    	List<String> result;
    	if (tournament.Format__c == '1 x 1') {
        	result = getPlayersIds(tournament.Id);
        } else {
        	result = getTeamsIds(tournament.Id);
        }
    	return result;
    }
    
    private List<String> getPlayersIds(String tournamentId) {
        List<String> result = new List<String>();
        List<PlayerTournament__c> playerTournaments = [SELECT Player__c 
            FROM PlayerTournament__c 
            WHERE Tournament__c = :tournamentId];
        for (PlayerTournament__c pT : playerTournaments) {
            result.add(pT.Player__c);
        }
        return result;
    }
    
    private List<String> getTeamsIds(String tournamentId) {
        List<String> result = new List<String>();
        List<Team__c> teams = [SELECT Id 
            FROM Team__c 
            WHERE Tournament__c = :tournamentId AND IsComplete__c = true];
        for (Team__c t : teams) {
            result.add(t.Id);
        }
        return result;
    }
    
}