src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AuthorizationController.cls
public class AuthorizationController {
    
    Public Player__c currentPlayer{
        get{
            if(currentPlayer == null) currentPlayer = new Player__c();   
            currentPlayer = getCurrentPlayer();
            return currentPlayer;
        }set;
    }
    
    public AuthorizationController(){
        
    }
    
    public Player__c getCurrentPlayer(){
        if(ApexPages.currentPage().getCookies().get('PlayerSession').getValue() !=null) 
        return [Select Id, Name, Email__c, IsManager__c From Player__c Where Id = :ApexPages.currentPage().getCookies().get('PlayerSession').getValue()];
        return new Player__c();
    }
    
    
    public PageReference loginUser(){
        List<Player__c> selectPlayer = [Select Status__c, Password__c from Player__c where Id = :currentPlayer.Id Limit 1];
        if(selectPlayer.size() > 0){
            if(selectPlayer.get(0).Status__c == 'active'){
                if(selectPlayer.get(0).Password__c != null && selectPlayer.get(0).Password__c == currentPlayer.Password__c){
                    Cookie ps = new Cookie('PlayerSession', currentPlayer.Id, null, 10000, false); //ps = player session
                    ApexPages.currentPage().setCookies(new Cookie[]{ps});
                    PageReference acctPage = new PageReference('/apex/Home');
                    acctPage.setRedirect(true);
                    return acctPage ;
                }else{ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Incorrect password'));
                      return null;}
            }else{ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'To begin with you must activate your account'));
                  return null;}
        }else {ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Incorect Email'));
               return null;}
    }
    
    public void logout(){
        
    }
    
}