src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PlayerTournament__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PlayerTournament</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>PlayerTournament Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PlayerTournaments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <picklist>
            <picklistValues>
                <fullName>1 x 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 x 2</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Upcoming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Round Robin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Elimination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double Elimination</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlayerTournamentController.cls
public with sharing class PlayerTournamentController {

	public Boolean isAlreadyApplied { get; set; }
        public Boolean isValidParameter { get; set; }
    
        public Tournament__c currentTournament { get; set; }
        public Player__c currentPlayer { get; set; }

	public PlayerTournamentController() {
		String tp = ApexPages.currentPage().getParameters().get('tp');
                isValidParameter = false;
                if (tp.length() == 36) {
                    String currentTournamentId = tp.substring(0, 18);
                    List<Tournament__c> tournaments = [SELECT Id, Name, Type__c, Format__c, Status__c, StartDate__c
                        FROM Tournament__c
                        WHERE Id = :currentTournamentId];
                    String currentPlayerId = tp.substring(18);
                    List<Player__c> players = [SELECT Id FROM Player__c WHERE Id = :currentPlayerId];
                    if (tournaments.size() > 0 && players.size() > 0) {
                        isValidParameter = true;
                        currentTournament = tournaments[0];
                        currentPlayer = players[0];
                    }
                }
	}

	public PageReference apply() {
		if (isValidParameter) {
                    List<PlayerTournament__c> playerTournaments = [SELECT Id FROM PlayerTournament__c 
                        WHERE Player__c = :currentPlayer.Id AND Tournament__c = :currentTournament.Id];
                    isAlreadyApplied = playerTournaments.size() > 0;
                    if (!isAlreadyApplied && currentTournament.Status__c == 'Upcoming') {
                        try {
                            PlayerTournament__c playerTournament = new PlayerTournament__c(Player__c = currentPlayer.Id, Tournament__c = currentTournament.Id);
                            insert (playerTournament);
                        } catch (Exception e) {
                            System.debug(e);
                        }
                    }
                    return null;
                }
                PageReference pR = Page.Home;
                pR.setRedirect(true);
		return pR;
	}

}