src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PlayerTeam__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>PlayerTeams</relationshipLabel>
        <relationshipName>PlayerTeams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>PlayerTeams</relationshipLabel>
        <relationshipName>PlayerTeams</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PlayerTeam</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>PlayerTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PlayerTeams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PlayerTournament__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PlayerTournament</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>PlayerTournament Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PlayerTournaments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <picklist>
            <picklistValues>
                <fullName>1 x 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 x 2</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Upcoming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Round Robin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Elimination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double Elimination</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TournamentController_TEST.cls
@isTest
public with sharing class TournamentController_TEST {

    public static TournamentController tC =  new TournamentController();
    public static Tournament__c t = new Tournament__c(Name='qwer', Type__c='Single Elimination', Format__c='1 x 1', StartDate__c=DateTime.now());
    public static Tournament__c t1 = new Tournament__c(Name='qwer', Type__c='', Format__c='1 x 1', StartDate__c=DateTime.now());

    public static testMethod void testSave() {
        tC.currentTournament = t;
        tC.save();
        tC.currentTournament = t1;
        tC.save();
        
        Test.startTest();
        
        //first succesfully inserted
        List<Tournament__c> ts = [SELECT Id FROM Tournament__c];
        System.assertEquals(1, ts.size());

        //second succesfully inserted        
        t1.Type__c = 'Double Elimination';
        tC.currentTournament = t1;
        tC.save();
        ts = [SELECT Id FROM Tournament__c];
        System.assertEquals(2, ts.size());
        
        
        //first succesfully edited
        t.Name='fhbsdf';
        tC.currentTournament = t;
        tC.save();
        ts = [SELECT Id FROM Tournament__c];
        System.assertEquals(2, ts.size());
        Test.stopTest();
    }
    
    public static testMethod void testFindByIdAndEditAndDelete(){
        t.Status__c = 'Upcoming';
        insert(t);
        tC.currentTournamentId = t.Id;
        
        Test.startTest();
        
        tC.editUpcoming();
        System.assertEquals(t.Id, tC.currentTournament.Id);
        
        List<Tournament__c> ts = [SELECT Id FROM Tournament__c];
        System.assertEquals(1, ts.size());
        
        tC.deleteUpcoming();
        System.assertEquals(t.Id, tC.currentTournament.Id);
        
        ts = [SELECT Id FROM Tournament__c];
        System.assertEquals(0, ts.size());
        
        Test.stopTest();
    }
    
    public static testMethod void testCheckTourExistance(){
        t.Status__c = 'Upcoming';
        insert t;
        Test.setCurrentPageReference(new PageReference('Page.EditTournament')); 
        System.currentPageReference().getParameters().put('tournamentId', t.Id);
        Player__c p = new Player__c(Email__c = 'vdv@vdv.dv', IsManager__c = true, Password__c = '1234567890', Name = 'bdf', Status__c = 'Active');
        insert (p);
        List<Player__c> players = [select Id,Password__c from Player__c where Email__c =: p.Email__c limit 1];
        System.debug(players);
        Cookie playerFromCookie = new Cookie('PlayerFromCookie', players.get(0).Id, null, 1440, false);
        System.currentPageReference().setCookies(new Cookie[]{playerFromCookie});
        TournamentController tC1 =  new TournamentController();
        
        Test.startTest();
        
        tC1.checkTournamentExistance();
        
        System.assertEquals(t.Id, tC1.currentTournament.Id);
        
        Test.stopTest();
    }
    
    public static testMethod void testFindAll(){
        tC.currentTournament = t;
        tC.save();
        t1.Type__c = 'Double Elimination';
        tC.currentTournament = t1;
        tC.save();
        
        Test.startTest();
        
        List<Tournament__c> ts = [SELECT Id FROM Tournament__c];
        System.assertEquals(2, ts.size());
        
        System.assertEquals(null, tC.currentPlayer);
        
        tC.search();
        System.assertEquals(2, tC.allTournaments.size());
        
        System.assertEquals(null, tC.currentPlayerTmp.Id);
        
        tC.searchTournament.Type__c='Single Elimination';
        tC.search();
        System.assertEquals(1, tC.allTournaments.size());
        
        Player__c player = new Player__c();
        player.Name = 'name';
        player.Email__c = 'sv@email.com';
        player.Password__c = 'password'; 
        insert(player);
        
        PlayerTournament__c pT = new PlayerTournament__c(Player__c = player.Id, Tournament__c = t.Id);
        insert(pT);
        
        tC.currentPlayer2 = player;
        tC.search();
        System.assertEquals(1, tC.allTournaments.size());
        System.assertEquals(true, tC.allTournaments[0].isApplied);
        System.assertEquals(false, tC.allTournaments[0].isShowed);
        
        Test.stopTest();        
    }

    public static testMethod void testView(){
        tC.currentTournament = t;
        tC.save();
        t1.Type__c = 'Double Elimination';
        tC.currentTournament = t1;
        tC.save();
        
        tC.search();
        
        tC.currentTournamentId = t.Id;
        
        Test.startTest();
        
        tC.view();
        
        Boolean isTShowed = false;
        
        for (TournamentController.TournamentWrapper tW : tC.allTournaments) {
            if (tW.tournament.Id == t.Id) {
                isTShowed = true;
                break;
            }
        }
        
        System.assertEquals(true, isTShowed);
        
        Test.stopTest();           
    }
    
    public static testMethod void testCancel() {
        PageReference pR = tC.cancel();
        Test.startTest();
        
        System.assertEquals(Page.Tournaments.getUrl(), pR.getUrl());
        
        Test.stopTest(); 
    }
    
    public static testMethod void testApply() {
        
        PageReference pR = tC.apply();
        
        Test.startTest();
        
        System.assertEquals(null, pR);
        
        t.Status__c = 'Upcoming';
        insert(t);
        tC.currentTournamentId = t.Id;
        pR = tC.apply();
        
        System.assertEquals(null, pR);
        
        Player__c p = new Player__c(Email__c = 'vdv@vdv.dv', IsManager__c = true, Password__c = '1234567890', Name = 'bdf', Status__c = 'Active');
        insert (p);
        List<Player__c> players = [select Id,Password__c from Player__c where Email__c =: p.Email__c limit 1];
        System.debug(players);
        Cookie playerFromCookie = new Cookie('PlayerFromCookie', players.get(0).Id, null, 1440, false);
        System.currentPageReference().setCookies(new Cookie[]{playerFromCookie});
        
        tC.search();
        
        pR = tC.apply();
        
        System.assertEquals(null, pR);
        
        List<PlayerTournament__c> pTs = [SELECt Id FROM PlayerTournament__c];
        
        System.assertEquals(1, pTs.size());
        
        Tournament__c t22 = new Tournament__c(Name='qwer', Type__c='Single Elimination', Format__c='2 x 2', StartDate__c=DateTime.now(), Status__c = 'Upcoming');
        insert(t22);
        tC.currentTournamentId = t22.Id;
        pR = tC.apply();
        
        System.assertEquals(Page.PlayerTeamCreate.getUrl() + '?tournamentId=' + t22.Id, pR.getUrl());
        
        Test.stopTest(); 
    }
    
    public static testMethod void testDisapply() {
        
        t.Status__c = 'Upcoming';
        insert(t);
        tC.currentTournamentId = t.Id;
        
        Player__c p = new Player__c(Email__c = 'vdv@vdv.dv', IsManager__c = true, Password__c = '1234567890', Name = 'bdf', Status__c = 'Active');
        insert (p);
        List<Player__c> players = [select Id,Password__c from Player__c where Email__c =: p.Email__c limit 1];
        System.debug(players);
        Cookie playerFromCookie = new Cookie('PlayerFromCookie', players.get(0).Id, null, 1440, false);
        System.currentPageReference().setCookies(new Cookie[]{playerFromCookie});
        
        tC.search();
        
        PageReference pR = tC.apply();
        
        System.assertEquals(null, pR);
        
        List<PlayerTournament__c> pTs = [SELECt Id FROM PlayerTournament__c];
        
        System.assertEquals(1, pTs.size());
        
        tC.currentTournamentId = null;
        tC.disApply();
        
        pTs = [SELECt Id FROM PlayerTournament__c];
        
        System.assertEquals(1, pTs.size());
        
        tC.currentTournamentId = t.Id;
        tC.disApply();
        
        pTs = [SELECt Id FROM PlayerTournament__c];
        
        System.assertEquals(0, pTs.size());
        
        Tournament__c t22 = new Tournament__c(Name='qwer', Type__c='Single Elimination', Format__c='2 x 2', StartDate__c=DateTime.now(), Status__c = 'Upcoming');
        insert(t22);
        tC.currentTournamentId = t22.Id;
        
        Team__c team = new Team__c(Name = 'grbgv', Tournament__c = t22.Id);
        insert(team);
        
        PlayerTeam__c pT = new PlayerTeam__c(Player__c = players.get(0).Id, Team__c = team.Id);
        insert(pT);
        
        List<Team__c> teams = [SELECT Id FROM Team__c WHERE Tournament__c = :tC.currentTournamentId AND 
                    Id IN (SELECT Team__c FROM PlayerTeam__c WHERE Player__c = :players.get(0).Id)];
        
        System.assertEquals(1, teams.size());
        
        tC.disApply();
        
        teams = [SELECT Id FROM Team__c WHERE Tournament__c = :tC.currentTournamentId AND 
                    Id IN (SELECT Team__c FROM PlayerTeam__c WHERE Player__c = :players.get(0).Id)];
        
        System.assertEquals(0, teams.size());
    }
    
}