src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PlayerTeam__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>PlayerTeams</relationshipLabel>
        <relationshipName>PlayerTeams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>PlayerTeams</relationshipLabel>
        <relationshipName>PlayerTeams</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PlayerTeam</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>PlayerTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PlayerTeams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Upcoming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlayerTeamController.cls
public with sharing class PlayerTeamController extends PlayerCookie{
    
    public PlayerTeam__c playerTeam { get; set; }
    public Team__c team { get; set; }
    
    public String currentPlayerId { get; set; }
    public List<Player__c> players { get; set; }
    public String selectedPlayer { get; set; }
    
    public LIst<SelectOption> playersOptions {get {
		if (playersOptions == null) {
			playersOptions = new List<SelectOption>();
			String tournamentId = ApexPages.currentPage().getParameters().get('tournamentId');
			List<Team__c> teams = [SELECT Name, (SELECT Player__c FROM PlayerTeams__r)
                            FROM Team__c WHERE Tournament__c = :tournamentId];
			for (Player__c p : players) {
				SelectOption selectOption;
				for (Team__c t : teams) {
					for (PlayerTeam__c pT : t.PlayerTeams__r) {
						if (pT.Player__c == p.Id) {
							selectOption = new SelectOption(p.Id, p.Name + '(' + t.Name + ')');
							SelectOption.setDisabled(true);
							break;
						}
					}
					if (selectOption != null) {
						break;
					}
				}
				if (selectOption == null) {
					selectOption = new SelectOption(p.Id, p.Name);
				}
				playersOptions.add(selectOption);
			}
		}
		return playersOptions;
	} set;}
    
    public PlayerTeamController() {
        currentPlayerId = getCurrentPlayer().Id;
        players = [SELECT Id, Name FROM Player__c WHERE Id != :currentPlayerId AND Status__c = 'Active'];
    }
    
}