src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GeneralController.cls
public class GeneralController {
    
    Public Player__c currentPlayer{
        get{
            if(currentPlayer == null) currentPlayer = new Player__c();   
            currentPlayer = getCurrentPlayer();
            return currentPlayer;
        }set;
        }
    
    public GeneralController(){
        
    }
    
    public Player__c getCurrentPlayer(){
        if(ApexPages.currentPage().getCookies().get('PlayerSession').getValue() !=null) 
        return [Select Id, Name, Email__c, IsManager__c From Player__c Where Id = :ApexPages.currentPage().getCookies().get('PlayerSession').getValue()];
        return new Player__c();
    }

}