src/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlayerCookie.cls
public with sharing abstract class PlayerCookie {
    public Player__c currentPlayer {get;set;}
    public Boolean isLoggedIn {get;set;}
    public PlayerCookie(){
       isLoggedIn = ApexPages.currentPage().getCookies().get('PlayerFromCookie')!=null;
       if (isLoggedIn) {
            Id playerId = ApexPages.currentPage().getCookies().get('PlayerFromCookie').getValue();
            currentPlayer = [select Id,Name,Email__c,Password__c from Player__c where Id = :playerId];
        } 
    }
}