src/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <picklist>
            <picklistValues>
                <fullName>1 x 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 x 2</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Upcoming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Round Robin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Elimination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Double Elimination</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TournamentPDFTest.cls
@isTest
public with sharing class TournamentPDFTest{

    public static testMethod void propertieTest(){
        Tournament__c myPDFTournament = new Tournament__c(Name ='PDF', Type__c='Single Elimination', Format__c = '1 x 1', StartDate__c = Datetime.now(), Status__c = 'Upcoming');
        insert myPDFTournament;
        ApexPages.currentPage().getHeaders().put('id', myPDFTournament.Id);
        
        TournamentPDF testPDFwrong = new TournamentPDF();
        Test.setCurrentPageReference(new PageReference('Page.TournamentPDF')); 
        System.currentPageReference().getParameters().put('id', myPDFTournament.Id);
        TournamentPDF testPDFright = new TournamentPDF();
        Map<String, String> competitorsMap = new Map<String, String>();
        competitorsMap = Helper.getIdAndNameMap(myPDFTournament);
    }
    
}